<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [6]:
%%sql

SELECT
  customerkey,
  orderdate,
  (quantity * netprice *exchangerate) AS net_revenue,
  COUNT (*) OVER (
    PARTITION BY customerkey
    ORDER BY orderdate
  ) AS running_order_count,
  AVG(quantity * netprice *exchangerate) OVER (
    PARTITION BY customerkey
    ORDER BY orderdate
  ) AS running_avg_revenue
FROM
  sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

,customerkey,orderdate,net_revenue,running_order_count,running_avg_revenue
0,15,2021-03-08,2217.41,1,2217.41
1,180,2018-07-28,525.31,1,525.31
2,180,2023-08-28,71.36,3,836.74
3,180,2023-08-28,1913.55,3,836.74
4,185,2019-06-01,1395.52,1,1395.52
...,...,...,...,...,...
199868,2099711,2016-08-13,2067.75,1,2067.75
199869,2099711,2017-08-14,3940.92,2,3004.34
199870,2099743,2022-03-17,375.57,2,234.81
199871,2099743,2022-03-17,94.05,2,234.81
199872,2099743,2023-02-11,598.46,3,356.03

In [15]:
%%sql

WITH row_numbering AS(
SELECT
  ROW_NUMBER() OVER(
    PARTITION BY
      orderdate
    ORDER BY
      orderdate,
      orderkey,
      linenumber
  ) AS row_num,
  *
FROM
  sales
)

SELECT
  *
FROM
  row_numbering
WHERE orderdate > '2015-01-01'
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,row_num,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1,2000,0,2015-01-02,2015-01-02,1639738,530,1613,5,65.99,59.39,33.65,USD,1.00
1,2,2001,0,2015-01-02,2015-01-15,2085372,999999,2182,2,1237.50,1237.50,410.01,USD,1.00
2,3,2002,0,2015-01-02,2015-01-02,1732602,510,1822,2,22.40,22.40,11.42,USD,1.00
3,4,2002,1,2015-01-02,2015-01-02,1732602,510,49,5,149.96,149.96,68.96,USD,1.00
4,5,2003,0,2015-01-02,2015-01-02,728917,300,1674,2,4.89,4.89,2.49,EUR,0.83
5,6,2003,1,2015-01-02,2015-01-02,728917,300,369,1,1747.50,1555.28,803.60,EUR,0.83
6,7,2004,0,2015-01-02,2015-01-02,1724183,570,1654,2,155.99,155.99,51.68,USD,1.00
7,8,2005,0,2015-01-02,2015-01-02,2054699,480,460,1,749.75,712.26,382.25,USD,1.00
8,1,3000,0,2015-01-03,2015-01-03,1793739,500,108,3,99.74,97.75,45.87,USD,1.00
9,2,3000,1,2015-01-03,2015-01-03,1793739,500,1684,3,11.82,11.00,3.92,USD,1.00

In [12]:
%%sql

SELECT
  ROW_NUMBER() OVER(
    PARTITION BY
      orderdate
    ORDER BY
      orderdate,
      orderkey,
      linenumber
  ) AS row_num,
  *
FROM
  sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

,row_num,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,2,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64
2,3,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00
3,4,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00
4,5,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199868,93,3398034,1,2024-04-20,2024-04-21,664396,999999,1651,7,159.99,139.19,73.57,EUR,0.94
199869,94,3398034,2,2024-04-20,2024-04-21,664396,999999,1646,1,159.99,159.99,73.57,EUR,0.94
199870,95,3398035,0,2024-04-20,2024-04-22,267690,999999,1575,2,60.99,53.67,28.05,CAD,1.38
199871,96,3398035,1,2024-04-20,2024-04-22,267690,999999,415,5,326.00,293.40,166.20,CAD,1.38
199872,97,3398035,2,2024-04-20,2024-04-22,267690,999999,1693,6,6.88,6.88,3.16,CAD,1.38

In [25]:
%%sql

SELECT
  customerkey,
  COUNT(*) AS total_order,
  ROW_NUMBER() OVER (ORDER BY COUNT(*) DESC) AS total_orders_row_num,
  RANK() OVER (ORDER BY COUNT(*) DESC) AS total_orders_rank,
  DENSE_RANK() OVER (ORDER BY COUNT(*) DESC) AS total_orders_rank
FROM
  sales
GROUP BY
  customerkey
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,customerkey,total_order,total_orders_row_num,total_orders_rank,total_orders_rank
0,1834524,31,1,1,1
1,1375597,30,2,2,2
2,249557,27,3,3,3
3,459519,26,4,4,4
4,1495941,26,5,4,4
5,1801215,26,6,4,4
6,1219056,25,7,7,5
7,759419,24,8,8,6
8,1427444,24,9,8,6
9,1876222,24,10,8,6

In [41]:
%%sql

WITH monthly_revenue AS (
SELECT
  TO_CHAR(orderdate, 'YYYY-MM') AS month,
  SUM(quantity * netprice * exchangerate) AS net_revenue
FROM sales
WHERE EXTRACT(YEAR FROM orderdate) = '2023'
GROUP BY
  month
ORDER BY
  month
)

SELECT
  *,
  FIRST_VALUE(net_revenue) OVER (ORDER BY month) AS first_month_rev,
  LAST_VALUE(net_revenue) OVER (ORDER BY month ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING ) AS last_month_rev,
  NTH_VALUE(net_revenue,3) OVER (ORDER BY month ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING ) AS last_month_rev
FROM
  monthly_revenue

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

      month  net_revenue  first_month_rev  last_month_rev  last_month_rev
0   2023-01   3664431.34       3664431.34      2928550.93      2244316.52
1   2023-02   4465204.57       3664431.34      2928550.93      2244316.52
2   2023-03   2244316.52       3664431.34      2928550.93      2244316.52
3   2023-04   1162796.16       3664431.34      2928550.93      2244316.52
4   2023-05   2943005.99       3664431.34      2928550.93      2244316.52
5   2023-06   2864500.03       3664431.34      2928550.93      2244316.52
6   2023-07   2337639.34       3664431.34      2928550.93      2244316.52
7   2023-08   2623919.79       3664431.34      2928550.93      2244316.52
8   2023-09   2622774.85       3664431.34      2928550.93      2244316.52
9   2023-10   2551322.61       3664431.34      2928550.93      2244316.52
10  2023-11   2700103.38       3664431.34      2928550.93      2244316.52
11  2023-12   2928550.93       3664431.34      2928550.93      2244316.52

Here are 5 practice problems:

### Problem 1: Calculate Total Revenue by Customer

Write a SQL query that returns the `customerkey` and the `total_revenue` for each customer, ordered by `total_revenue` in descending order. `total_revenue` should be calculated as `SUM(quantity * netprice * exchangerate)`.

### Problem 2: Find the Top 3 Products by Sales Quantity in a Specific Year

Write a SQL query to identify the top 3 `productkey`s that had the highest total `quantity` sold in the year `2022`. The result should show `productkey` and `total_quantity`, ordered by `total_quantity` in descending order.

### Problem 3: Monthly Sales Growth Percentage

Write a SQL query to calculate the month-over-month sales growth percentage for the year `2023`. The query should return the `month`, `current_month_revenue`, `previous_month_revenue`, and `growth_percentage`. `growth_percentage` should be `((current_month_revenue - previous_month_revenue) / previous_month_revenue) * 100`.

### Problem 4: Customers Who Purchased More Than Once

Write a SQL query to find all `customerkey`s who have placed more than one order. The query should return the `customerkey` and `order_count`, ordered by `customerkey`.

### Problem 5: Average Order Value Per Store

Write a SQL query to calculate the average order value (`AVG(quantity * netprice * exchangerate)`) for each `storekey`. The results should be ordered by `storekey`.

In [99]:
%%sql

SELECT
  storekey,
  AVG((quantity * netprice * exchangerate)) AS average_order_value
FROM
  sales
GROUP BY
  storekey
ORDER BY
  storekey

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

72 rows affected.

    storekey  average_order_value
0         10              1431.11
1         20              1975.40
2         30              1600.15
3         35              1534.03
4         40              1393.16
..       ...                  ...
67       630              1131.93
68       650              1030.70
69       660              1048.34
70       670              1091.14
71    999999               980.73

[72 rows x 2 columns]

In [92]:
%%sql

SELECT
  customerkey,
  COUNT(*) AS order_count
FROM
  sales
GROUP BY
  customerkey
HAVING
  COUNT(*) >1
ORDER BY
  customerkey

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

39984 rows affected.

       customerkey  order_count
0              180            3
1              387            9
2              406            2
3              545            6
4              649            6
...            ...          ...
39979      2099619            8
39980      2099656           13
39981      2099697            3
39982      2099711            2
39983      2099743            3

[39984 rows x 2 columns]

In [ ]:
%%sql

SELECT
  customerkey,
  COUNT(*) AS order_count
FROM
  sales
GROUP BY
  customerkey
HAVING
  COUNT(*) > 1
ORDER BY
  customerkey;

In [ ]:
%%sql

SELECT
  storekey,
  AVG(quantity * netprice * exchangerate) AS average_order_value
FROM
  sales
GROUP BY
  storekey
ORDER BY
  storekey;

### 2. Window Functions (General - `OVER (PARTITION BY ... ORDER BY ...)`)

**When to use:** When you need to perform a calculation across a set of related table rows (the "window") without collapsing those rows. Unlike `GROUP BY`, window functions return a value for *each individual row*, while still allowing calculations based on other rows in its window.

**Keywords/Scenarios:**
*   "Running total/average"
*   "Percentage of total for each row"
*   "Calculate something based on other rows in the same group, but keep all original rows"
*   "Comparison of a row's value to the group's average/total"

### 3. Ranking (`RANK()`, `DENSE_RANK()`, `ROW_NUMBER()`, `NTILE()`)

**When to use:** A specific type of window function used to assign a rank to rows within an ordered partition (group).

**Keywords/Scenarios:**
*   "Top N items within each category"
*   "Rank customers by their spending"
*   "Find the 1st, 2nd, or 3rd highest/lowest values"
*   "Assign a unique number to each row within a group"

### 4. `LAG()` and `LEAD()`

**When to use:** Specific window functions used to access data from a preceding (`LAG`) or succeeding (`LEAD`) row within the same ordered result set.

**Keywords/Scenarios:**
*   "Month-over-month sales growth"
*   "Compare current value to previous period's value"
*   "Identify changes or trends between consecutive entries"
*   "Previous order date for each customer"
*   "Next step in a process"

### 5. Frame Clauses (`ROWS BETWEEN ... AND ...`, `RANGE BETWEEN ... AND ...`)

**When to use:** Used *with* window functions (especially aggregate window functions like `AVG`, `SUM`) to precisely define the subset of rows within the window that the function should operate on. This creates a "sliding window" or "moving average/sum."

**Keywords/Scenarios:**
*   "Moving average over the last 3 days"
*   "Running sum up to the current row"
*   "Calculate an average of the current row and its 2 preceding rows"
*   Often used for time-series analysis to smooth data or identify trends over a defined period.

### 6. Pivot with `CASE` (or `PIVOT` operator)

**When to use:** When you need to transform rows into columns. This is typically used to create a more compact, summary view where distinct values from one column become new columns, and an aggregate function is applied to the values in those new columns.

**Keywords/Scenarios:**
*   "Show sales for each product category as separate columns (e.g., `Sales_Electronics`, `Sales_Clothing`)"
*   "Summarize data by putting unique values from a categorical column into headers"
*   "Convert long format data to wide format data"

By looking for these keywords and understanding the goal (summarize all into one row per group, calculate per row without collapsing, rank, compare to previous/next, or reshape data), you can often pinpoint the right SQL tool!

In [84]:
%%sql

WITH monthly_revenue AS (
  SELECT
    EXTRACT(MONTH FROM orderdate) AS month,
    SUM(quantity * netprice * exchangerate) AS current_month_revenue
  FROM
    sales
  WHERE EXTRACT(YEAR FROM orderdate) = 2023
  GROUP BY
    month
  ORDER BY
    month
)
SELECT
  month,
  current_month_revenue,
  LAG(current_month_revenue) OVER (ORDER BY month) AS previous_month_revenue,
  ((current_month_revenue - LAG(current_month_revenue) OVER (ORDER BY month)) / LAG(current_month_revenue) OVER (ORDER BY month)) * 100 AS growth_percentage
FROM monthly_revenue

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

   month  current_month_revenue  previous_month_revenue  growth_percentage
0      1             3664431.34                     NaN                NaN
1      2             4465204.57              3664431.34              21.85
2      3             2244316.52              4465204.57             -49.74
3      4             1162796.16              2244316.52             -48.19
4      5             2943005.99              1162796.16             153.10
5      6             2864500.03              2943005.99              -2.67
6      7             2337639.34              2864500.03             -18.39
7      8             2623919.79              2337639.34              12.25
8      9             2622774.85              2623919.79              -0.04
9     10             2551322.61              2622774.85              -2.72
10    11             2700103.38              2551322.61               5.83
11    12             2928550.93              2700103.38               8.46

In [ ]:
%%sql

SELECT
  productkey,
  SUM(quantity) AS total_quantity
FROM
  sales
WHERE
  EXTRACT(YEAR FROM orderdate) = 2022
GROUP BY
  productkey
ORDER BY
  total_quantity DESC
LIMIT 3

In [46]:
%%sql

WITH monthly_revenue AS (
SELECT
  TO_CHAR(orderdate, 'YYYY-MM') AS month,
  SUM(quantity * netprice * exchangerate) AS net_revenue
FROM sales
WHERE EXTRACT(YEAR FROM orderdate) = '2023'
GROUP BY
  month
ORDER BY
  month
)

SELECT
  *,
  LAG(net_revenue) OVER (ORDER BY month) AS previous_month_rev,
  LEAD(net_revenue) OVER (ORDER BY month) AS next_month_rev
  FROM
  monthly_revenue

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

      month  net_revenue  previous_month_rev  next_month_rev
0   2023-01   3664431.34                 NaN      4465204.57
1   2023-02   4465204.57          3664431.34      2244316.52
2   2023-03   2244316.52          4465204.57      1162796.16
3   2023-04   1162796.16          2244316.52      2943005.99
4   2023-05   2943005.99          1162796.16      2864500.03
5   2023-06   2864500.03          2943005.99      2337639.34
6   2023-07   2337639.34          2864500.03      2623919.79
7   2023-08   2623919.79          2337639.34      2622774.85
8   2023-09   2622774.85          2623919.79      2551322.61
9   2023-10   2551322.61          2622774.85      2700103.38
10  2023-11   2700103.38          2551322.61      2928550.93
11  2023-12   2928550.93          2700103.38             NaN

In [59]:
%%sql

WITH monthly_sales AS (
  SELECT
    TO_CHAR(orderdate, 'YYYY-MM') AS month,
    SUM(quantity * netprice * exchangerate) AS net_revenue
  FROM sales
  WHERE EXTRACT(YEAR FROM orderdate) = '2023'
  GROUP BY
    month
  ORDER BY
    month
)

SELECT
  month,
  net_revenue,
  AVG(net_revenue) OVER(
    ORDER BY month
    ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING
  ) AS net_rev_preceding_1,

FROM
  monthly_sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

,month,net_revenue,net_rev_preceding_1,net_rev_preceding_2,net_rev_preceding_3
0,2023-01,3664431.34,4064817.96,3457984.14,2884187.15
1,2023-02,4465204.57,3457984.14,2884187.15,2895950.92
2,2023-03,2244316.52,2624105.75,2895950.92,2890709.10
3,2023-04,1162796.16,2116706.22,2735964.65,2811699.14
4,2023-05,2943005.99,2323434.06,2310451.61,2663054.63
5,2023-06,2864500.03,2715048.45,2386372.26,2399850.38
6,2023-07,2337639.34,2608686.39,2678368.00,2443708.40
7,2023-08,2623919.79,2528111.33,2600031.32,2663323.71
8,2023-09,2622774.85,2599339.08,2567151.99,2661258.70
9,2023-10,2551322.61,2624733.61,2685334.31,2627385.15
10,2023-11,2700103.38,2726658.97,2700687.94,2685334.31
11,2023-12,2928550.93,2814327.15,2726658.97,2700687.94